# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'message_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15message_service.proto\x12\x07message\"\x1e\n\x0eMessageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\")\n\x0fMessageResponse\x12\x16\n\x0eprocessed_text\x18\x01 \x01(\t2U\n\x0eMessageService\x12\x43\n\x0eProcessMessage\x12\x17.message.MessageRequest\x1a\x18.message.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=34
  _globals['_MESSAGEREQUEST']._serialized_end=64
  _globals['_MESSAGERESPONSE']._serialized_start=66
  _globals['_MESSAGERESPONSE']._serialized_end=107
  _globals['_MESSAGESERVICE']._serialized_start=109
  _globals['_MESSAGESERVICE']._serialized_end=194
# @@protoc_insertion_point(module_scope)