# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import music_pb2 as music__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in music_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )

class MusicPlayerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamPlaylist = channel.unary_stream(
                '/music.MusicPlayer/StreamPlaylist',
                request_serializer=music__pb2.PlaylistRequest.SerializeToString,
                response_deserializer=music__pb2.TrackResponse.FromString,
                _registered_method=True)

class MusicPlayerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

def add_MusicPlayerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamPlaylist': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPlaylist,
                    request_deserializer=music__pb2.PlaylistRequest.FromString,
                    response_serializer=music__pb2.TrackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'music.MusicPlayer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('music.MusicPlayer', rpc_method_handlers)

 # This class is part of an EXPERIMENTAL API.
class MusicPlayer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/music.MusicPlayer/StreamPlaylist',
            music__pb2.PlaylistRequest.SerializeToString,
            music__pb2.TrackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
